### ISSUE TITLE
Scraping jobs are broken-ish

### ISSUE THREAD

**Issue by howdoicomputer** [codeforsanjose/findahome#23]
Two things are happening:

1. Listings are being queued up twice. The first entry is the URL and the second entry is a URL with its listing ID at the end as an HTTP parameter. See imgur link below.

http://imgur.com/a/wWk5l

There should only be one job per link and the `nil` should the listing id. This was working previously and I'm not sure what broke.

2. The jobs started failing around six jobs in. Stacktrace below. Looks like some error with parsing the address; the code is trying to match a string that doesn't exist.

I'm wondering if there are new listings that have a format that is different from the others and it's causing some parsing errors.

```
2017-02-28T23:05:42.017Z 2283 TID-ox6qaxdnw WARN: {"context":"Job raised exception","job":{"class":"ListingJob","args":["http://www.socialserve.com/dbh/ViewUnit/852431?hm=d2II5vgH",null],"retry":2,"queue":"default","jid":"8e96b47ae7437e7a89ee4b51","created_at":1488322541.0403042,"enqueued_at":1488323141.7282197,"error_message":"undefined method `match' for nil:NilClass\nDid you mean?  catch","error_class":"NoMethodError","failed_at":1488323142.0172186,"retry_count":0},"jobstr":"{\"class\":\"ListingJob\",\"args\":[\"http://www.socialserve.com/dbh/ViewUnit/852431?hm=d2II5vgH\",null],\"retry\":2,\"queue\":\"default\",\"jid\":\"8e96b47ae7437e7a89ee4b51\",\"created_at\":1488322541.0403042,\"enqueued_at\":1488323141.7282197}"}
2017-02-28T23:05:42.017Z 2283 TID-ox6qaxdnw WARN: NoMethodError: undefined method `match' for nil:NilClass
Did you mean?  catch
2017-02-28T23:05:42.017Z 2283 TID-ox6qaxdnw WARN: /home/howdoicomputer/workspace/per/findahome/lib/social_crawler/listing.rb:293:in `parse_address'
/home/howdoicomputer/workspace/per/findahome/lib/social_crawler/listing.rb:55:in `fetch_listing_metadata'
/home/howdoicomputer/workspace/per/findahome/app/jobs/listing_job.rb:26:in `perform'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:158:in `execute_job'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:138:in `block (4 levels) in process'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq.rb:36:in `block in <module:Sidekiq>'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:133:in `block (3 levels) in process'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:128:in `block in invoke'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/logging.rb:32:in `with_context'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:130:in `block in invoke'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/middleware/chain.rb:133:in `invoke'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:132:in `block (2 levels) in process'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:174:in `stats'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:131:in `block in process'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/rails.rb:106:in `block in call'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/reloader.rb:68:in `block in wrap'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/execution_wrapper.rb:85:in `wrap'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/reloader.rb:67:in `wrap'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/rails.rb:105:in `call'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:126:in `process'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:82:in `process_one'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/processor.rb:70:in `run'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:17:in `watchdog'
/home/howdoicomputer/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb:26:in `block in safe_thread'
```

**Comment by howdoicomputer** [comment]
As far as the duplicate links, it looks like Social Serve changed their site so that they have duplicate links.

I'll strip the ends of ViewUnit URLs and then dedup the resulting list as a fix.

**Comment by howdoicomputer** [comment]
The second error comes from the `parse_one_to_one` method that matches up matches to an array of match datums.

It looks like that the jobs that are failing are hitting links that have an element sharing the table cell of the 'Property Type' string. Since social serve developers haven't' heard of HTML element ids, most of the parsing logic follows an 'if a match is found then grab the next element' pattern so I wouldn't be surprised if this incosistency is messing things up.

Would maybe a longer term solution is to relax the code a bit so that `nil` values are better handled and we only fail on 'crucial' pieces of data. This sounds much more preferable - especially since job batches subsequent from the first will update listing records in postgres only if that record doesn't exist.
